#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  vim:ts=4:sts=4:sw=4:et

language: perl
perl:
  - "5.22"
  # this build has thread support
  - "5.18-shrplib"
  #- "5.16"
  # Redis module now requires Perl 5.10
  - "5.10"
  #- "5.8"

sudo: required

notifications:
  email: false

branches:
  only:
    - master

services:
  - docker

install:
  #- pushd lib
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM LIB FAILED
  #- popd
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM FAILED
  # fixed core build to switch to cpanm for speed
  - make

after_success:
  - curl -ivv --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/tools/trigger/6b4c6eeb-ed48-4e01-954f-ec2e0692ca35/
  - curl -ivv --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/centos-github/trigger/316d1158-7ffb-49a4-a7bd-8e5456ba2d15/
  - curl -ivv --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/ubuntu-github/trigger/abd4dbf0-14bc-454f-9cde-081ec014bc48/
  - curl -ivv --data {build:true} -X POST https://registry.hub.docker.com/u/harisekhon/debian-github/trigger/0cfb3fe7-2028-494b-a43b-068435e6a2b3/
