#
#  Author: Hari Sekhon
#  Date: 2014-11-29 01:02:47 +0000 (Sat, 29 Nov 2014)
#
#  vim:ts=4:sts=4:sw=4:et

language: perl
perl:
  # this build has thread support
  - "5.24-shrplib"
  #- "5.22"
  #- "5.18-shrplib"
  #- "5.16"
  # Redis module now requires Perl 5.10
  - "5.10"
  #- "5.8"

sudo: required

notifications:
  email: false

branches:
  only:
    - master

env:
  #- DEBUG=1
  - DOCKER_COMPOSE_VERSION=1.16.1 PYTHONUNBUFFERED=1

services:
  - docker

install:
  #- pushd lib
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM LIB FAILED
  #- popd
  #- make apt-packages
  #- cpanm --installdeps --notest . || echo CPANM FAILED
  # fixed core build to switch to cpanm for speed
  - travis_retry make

script:
  - travis_retry make test

after_success:
  # Tools
  - curl --header "Content:Type:application/json" --data '{"build":true}' -X POST https://cloud.docker.com/api/build/v1/source/1ce5ac1d-4ce6-4051-8246-2e05e042dfd7/trigger/6b4c6eeb-ed48-4e01-954f-ec2e0692ca35/call/
  # Alpine Github
  - curl --header "Content:Type:application/json" --data '{"build":true}' -X POST https://cloud.docker.com/api/build/v1/source/df816f2a-9407-4f1b-8b51-39615d784e65/trigger/8d9cb826-48df-439c-8c20-1975713064fc/call/
  # Debian Github
  - curl --header "Content:Type:application/json" --data '{"build":true}' -X POST https://cloud.docker.com/api/build/v1/source/439eff84-50c7-464a-a49e-0ac0bf1a9a43/trigger/0cfb3fe7-2028-494b-a43b-068435e6a2b3/call/
  # CentOS Github
  - curl --header "Content:Type:application/json" --data '{"build":true}' -X POST https://cloud.docker.com/api/build/v1/source/efba1846-5a9e-470a-92f8-69edc1232ba0/trigger/316d1158-7ffb-49a4-a7bd-8e5456ba2d15/call/
  # Ubuntu Github
  - curl --header "Content:Type:application/json" --data '{"build":true}' -X POST https://cloud.docker.com/api/build/v1/source/8b3dc094-d4ca-4c92-861e-1e842b5fac42/trigger/abd4dbf0-14bc-454f-9cde-081ec014bc48/call/
